version: 2.1

orbs:
  bitcartcc: bitcartcc/bitcartcc-shared@1

jobs:
  lint:
    docker:
      - image: cimg/python:3.7

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-lint-dependencies-{{ .Branch }}-{{ checksum "~/.pyenv/version" }}

      - restore_cache:
          keys:
            - v1-lint-pre-commit-{{ .Branch }}-{{ checksum ".pre-commit-config.yaml" }}

      - run:
          name: install dependencies
          command: |
            virtualenv ~/venv
            echo ". ~/venv/bin/activate" >> $BASH_ENV
            source $BASH_ENV
            pip install -U -r generator/test-requirements.txt

      - save_cache:
          paths:
            - ~/venv
          key: v1-lint-dependencies-{{ .Branch }}-{{ checksum "~/.pyenv/version" }}

      - run:
          name: run pre-commit checks
          command: |
            pre-commit run --all-files --show-diff-on-failure
      - save_cache:
          paths:
            - ~/.cache/pre-commit
          key: v1-lint-pre-commit-{{ .Branch }}-{{ checksum ".pre-commit-config.yaml" }}

  test:
    docker:
      - image: cimg/python:3.7

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            cd generator
            pip install -r requirements.txt
            pip install -r test-requirements.txt

      - run:
          name: run tests
          command: |
            make ci
            codecov

  cansetup:
    executor: bitcartcc/build-ubuntu
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Test installation
          command: |
            cd .circleci
            sudo ./test-install.sh
  deploy:
    executor: bitcartcc/build-ubuntu

    environment:
      BUILD_PLATFORMS: linux/amd64,linux/arm/v7,linux/arm64/v8

    working_directory: ~/repo

    steps:
      - checkout
      - bitcartcc/login-to-dockerhub
      - bitcartcc/enable-buildx
      - run:
          name: build docker image
          command: |
            cd generator
            docker buildx build --progress plain --push --platform ${BUILD_PLATFORMS} --tag bitcartcc/docker-compose-generator:latest .

workflows:
  version: 2
  build:
    jobs:
      - lint
      - test:
          requires:
            - lint
      - cansetup:
          requires:
            - test
      - deploy:
          context: global
          requires:
            - cansetup
          filters:
            branches:
              only: master
