version: 2
jobs:
  cansetup:
    docker:
      - image: circleci/python:3.7
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Test installation
          command: |
            cd .circleci
            sudo ./test-install.sh
  deploy:
    docker:
      - image: circleci/python:3.7
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: build docker image
          command: |
            cd generator
            docker build -t bitcartcc/docker-compose-generator:latest .
            docker login --username=$DOCKER_USER --password=$DOCKER_PASS
            docker push bitcartcc/docker-compose-generator:latest

workflows:
  version: 2
  build:
    jobs:
      - cansetup
      - deploy:
          context: global
          requires:
            - cansetup
          filters:
            branches:
              only: master
