services:
  binancecoin:
    restart: unless-stopped
    image: bitcartcc/bitcart-bnb:stable
    environment:
      BNB_NETWORK: ${BNB_NETWORK:-mainnet}
      BNB_SERVER: ${BNB_SERVER:-https://bsc-dataseed.binance.org}
    expose:
      - "5006"
    volumes:
      - "binancecoin_datadir:/data"

  backend:
    depends_on:
      - binancecoin
    links:
      - binancecoin

volumes:
  binancecoin_datadir:
