services:
  bitcoincash:
    restart: unless-stopped
    image: bitcartcc/bitcart-bch:stable
    environment:
      BCH_NETWORK: ${BCH_NETWORK:-mainnet}
    expose:
      - "5004"
    volumes:
      - "bitcoincash_datadir:/data"

  backend:
    depends_on:
      - bitcoincash
    links:
      - bitcoincash

volumes:
  bitcoincash_datadir:
