services:
  gravity:
    restart: unless-stopped
    image: bitcartcc/bitcart-gzro:stable
    environment:
      GZRO_NETWORK: ${GZRO_NETWORK:-mainnet}
      GZRO_LIGHTNING: ${GZRO_LIGHTNING:-false}
    expose:
      - "5002"
    volumes:
      - "gravity_datadir:/data"

  backend:
    depends_on:
      - gravity
    links:
      - gravity

volumes:
  gravity_datadir:
