services:
  litecoin:
    restart: unless-stopped
    image: bitcartcc/bitcart-ltc:stable
    environment:
      LTC_NETWORK: ${LTC_NETWORK:-mainnet}
      LTC_LIGHTNING: ${LTC_LIGHTNING:-false}
    expose:
      - "5001"
    volumes:
      - "litecoin_datadir:/data"

  backend:
    depends_on:
      - litecoin
    links:
      - litecoin

volumes:
  litecoin_datadir:
