services:
  worker:
    restart: unless-stopped
    image: bitcartcc/bitcart:stable
    command: python3 worker.py
    environment:
      LOG_FILE: logs/bitcart-log.log
      BITCART_CRYPTOS: ${BITCART_CRYPTOS:-btc}
      BTC_NETWORK: ${BTC_NETWORK:-mainnet}
      BTC_LIGHTNING: ${BTC_LIGHTNING:-false}
      BCH_NETWORK: ${BCH_NETWORK:-mainnet}
      LTC_NETWORK: ${LTC_NETWORK:-mainnet}
      LTC_LIGHTNING: ${LTC_LIGHTNING:-false}
      GZRO_NETWORK: ${GZRO_NETWORK:-mainnet}
      GZRO_LIGHTNING: ${GZRO_LIGHTNING:-false}
      BSTY_NETWORK: ${BSTY_NETWORK:-mainnet}
      BSTY_LIGHTNING: ${BSTY_LIGHTNING:-false}
    volumes:
      - ./conf:/app/conf
      - ./logs:/app/logs
